services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    # Pre-seed script is required as a volume to load mock database
<<<<<<< HEAD
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
=======
>>>>>>> origin/eric/stats-feature
    # Data inside the container is lost on restart unless you persist it with a volume.
    ports:
      - "5432:5432"

  backend:
<<<<<<< HEAD
    # TODO: you will need to add to this 
    build: ./backend
    ports:
      - "5000:5000"  
    environment:
      DB_HOST: db                 # service name of the database container
      DB_NAME: marksdb            # matches POSTGRES_DB in db service
      DB_USER: marksuser          # matches POSTGRES_USER
      DB_PASSWORD: markspass      # matches POSTGRES_PASSWORD
    depends_on:
      - db


  frontend:
    # TODO: you will need to add to this
    build: ./frontend
    ports: 
      - "8080:80"
=======
    # TODO: you will need to add to this

  frontend:
    # TODO: you will need to add to this
>>>>>>> origin/eric/stats-feature

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug
